dist: precise
sudo: required
language: android
addons:
  hostname: builder
android:
  components:
  - build-tools-23.0.1
git:
  depth: 50
jdk:
- openjdk6
- oraclejdk8
env:
  matrix:
  - DEPLOY=true  VER_SUF=      EXTRA=
  - DEPLOY=false VER_SUF=_dex  EXTRA=-DANDROID_HOME=$ANDROID_HOME
before_install:
- wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.8-bin.tar.gz
- tar xzf apache-ant-1.9.8-bin.tar.gz
- wget https://services.gradle.org/distributions/gradle-2.10-bin.zip
- unzip gradle-2.10-bin.zip
- export GRADLE_HOME=$PWD/gradle-2.10
notifications:
  email:
    recipients:
    - devel@makewave.com
    on_success: always
  slack:
    rooms:
      secure: "aPlxQLIbdlWdopMiuFmKvceKsgQ7YfB0XTh5SlVHdoJdi4IdovDbk9b6BoEka5hRAQTW8Px4vPQLR90VzQeTlCiDZyRhZVlVTdQaaOLEY5kBRfATWOEYiVReqG2s7rsxUH6s4OSYA/NVAkK6d2nOWttb72DDy8rdFT068guCUSpkdKku5p2MCPe8nQnvJRtAgJBimxUNdwI+Eb77s0I2YKQqyl6b80IgWrBv/TsgxGKWmOPYKtx16CdBuDZKhOq4oIqLbveTGlRBiCrzBBL2DFZJxCMtzhROlF8Rf6FGIl5YF2q0KkWIeEhCo3jqJ6fU9fWCSn3Lq//vlJK+QLHTA5k5OH+Worf/hiP+arY4ixRuNyknHHUc4jemCTo1d6/VI7ft+Cgz36FHPnTf1wB/fMJ8H7errnGU8zc4ymgESnDFoBAgxsU+4/rvVReBuNieVNGXEQ4jieJyr3K1HfEyZHRS+H6vKKRacYU6zssTFJEqKBWUXNXDX4wjXjsQSdgTF029QEKWA2ZkE0tWFMAj41xv6bZ6tWFllZR7COtXJH+Cq3DwcRA0CIIvQ5u3fyDP2QNm0MLOXkp+Tbeur27fHXWKCCfSGge3yIWzLQh83TIKKgzTIQoCZ3WpQqXttAPqzwu9VgxpZqo5TpNpsFwovlh6l+zLeT2E+29vjT0Cv48="
    on_success: always 
install: true
script: apache-ant-1.9.8/bin/ant -Dbuild.kind=Travis_CI_$TRAVIS_JDK_VERSION -Dtravis.tag=$TRAVIS_TAG -Dtravis.suffix=$VER_SUF -Dgit.pristine=true -Dtravis.deploy=$DEPLOY $EXTRA distrib && ! (grep '<case ' out/distrib_*/junit_grunt/index.xml | grep -v passed)
before_deploy:
- openssl aes-256-cbc -K $encrypted_a3ffaab67d90_key -iv $encrypted_a3ffaab67d90_iv -in tools/travis/id_rsa.travis.enc -out tools/travis/id_rsa.travis -d
- chmod 600 tools/travis/id_rsa.travis
deploy:
- provider: releases
  api_key:
    secure: "iR1vVDQRXjlcqEmPNj8gNpt8tEjW+PuBUBkNAZpwFqtFTyhdj43PNs65imPUwFvBGRE976eMGFG+BP/d2JSbDJbBfyjZFJTl7YiwvhT00QRu7fv3zvpj4EEFh/6JG31C6dMlhgnm6scN/q4pH65/oubT4vuU9F5ODUemE7k4AcA6isACrPxXYHc0V5ulk1aVrt/fnxWHLF5N/Egj80Hk0ZiC/4zRlM+0TJTEnhGusH4SyGrkykQMvuVdi/qo1Ak8Ler2HKEie5XrIHfnwAPND+jxDdThrdyaLlivgy+ZO3FIM4Th5YN7KBfVuqvLxB3s3811zEr//hMvTjaGcnIOEfh4KF3oF42k9tp7xq846pFvcDxUsLLHN5vgKiB1TPWSWdVlV5wxjED8uNQEchH2shrsTas+Cr2GV6G9HUOPXSTHMe7quahfXwvLn+mBaCXIEX8e9kJCOLwCgSQbGB+PP+WZc/3tqUrlTOx7tO3zbKaF6QKEjaz3WjmfZl78cSXvaU9WSU0l3lrZmgvDtnXDJKz0e7iqSlJrvQcyorAVQc897N1/rdd2pBXUAfyFa4j609nY2xn3mo7uAHBK1/q1ZeU1y4RuaIkEXR+r/EGyuiyL1+NnrFtOC4fnlABveKQBbExHYuoMcUlPJl/Gx/1SUgcH8XK7272kjmfjYX/1KYc="
  file:
  - out/distrib_$TRAVIS_TAG$VER_SUF/knopflerfish_osgi_sdk_$TRAVIS_TAG$VER_SUF.jar
  - out/distrib_$TRAVIS_TAG$VER_SUF/knopflerfish_osgi_tiny_$TRAVIS_TAG$VER_SUF.zip
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk6
    condition: $DEPLOY = true
- provider: script
  script: tools/travis/kf_upload.sh $TRAVIS_TAG$VER_SUF
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk6
    condition: $DEPLOY = true
